### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by Boeing787-8** [Boeing787-8/furima-29312#9]
入力内容 | 備考
-- | --
自身のフリマアプリのURL |  https://git.heroku.com/furima--29312.git
Basic認証のIDとパスワード | BASIC_AUTH_PASSWORD:      29312 BASIC_AUTH_USER:          techcamp83
出品者用のメールアドレスとパスワード | aaa@bbb.ccc / aaa111
購入者用のメールアドレスとパスワード | 123@bbb.ccc / aaa111
購入用カードの番号・期限・セキュリティコード | 4242424242424242 / 3 23 / 123

**Comment by Boeing787-8** [comment]
Web URL:        https://furima--29312.herokuapp.com/

**Comment by mutorisa** [comment]
森屋さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

**[修正依頼箇所]**
**①Basic認証を導入しましょう。**

**②正常に新規登録できるようにしましょう。**
現状エラーが出てしまう状態です。
<img width="596" alt="スクリーンショット 2020-10-02 10 55 12" src="https://user-images.githubusercontent.com/65144927/94880499-0dee5880-049e-11eb-8610-a55be7a08da7.png">


**③Issueに記載されているメールアドレスやパスワードを入力してもログインすることができない状態です。正常にログインできるようにしましょう。**


修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by Boeing787-8** [comment]
修正致しましたのでご確認をお願い致します。
また、出品者用のメールアドレスは、bbb@bbb.cccに、パスワードは、aaa111に変更されました。

**Comment by Boeing787-8** [comment]
ベーシック認証の導入が完了し、ブラウザで確認済みです。

**Comment by Boeing787-8** [comment]
herokuのリセットをするコマンドを実行したので、出品者と購入者が変わりました。
出品者　123@aaa.bbb
購入者　bbb@bbb.ccc

**Comment by Boeing787-8** [comment]
パスワードは以前と同じaaa111です。

**Comment by keisukekodama** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします**。
